#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Gera data/homebrew.json — catalogo de HOMEBREW para Xbox original e Xbox 360.

Diferente das listas comerciais, nao existe fonte unica canonica para homebrew.
Os dados abaixo foram levantados manualmente (WebSearch/WebFetch) a partir de:
  - consolemods.org (wiki de modding do Xbox e do Xbox 360)
  - xboxdevwiki.net / free60project.github.io
  - Emulation General Wiki (emulation.gametechwiki.com)
  - GitHub (XboxDev/nxdk, Rocky5, Free60Project, libretro, xbmc)
  - Wikipedia (Kodi, XBMC4Xbox, Xbox Linux, Free60, artigos dos jogos/emuladores base)
  - arquivos do xbox-scene.com via web.archive.org

Para estender: acrescente uma tupla na lista ENTRIES e rode novamente.
Formato da tupla:
    (slug, console, title, wiki, year, category, developers, description, url, verified)

  slug        -> vira "hb-<slug>"; minusculo, [a-z0-9-]
  console     -> "xbox" | "x360" | "both"
  wiki        -> titulo do artigo na Wikipedia EN (para buscar imagem) ou None
  year        -> ano do primeiro lancamento conhecido, ou None (nunca chutar)
  category    -> dashboard | emulator | port | game | utility | media
  developers  -> lista de strings
  verified    -> "high" (fonte direta) | "medium" (bem conhecido, fonte indireta)
"""
import json
import os
import re
import sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "homebrew.json")

CONSOLES = {"xbox", "x360", "both"}
CATEGORIES = {"dashboard", "emulator", "port", "game", "utility", "media"}
VERIFIED = {"high", "medium"}

# ---------------------------------------------------------------------------
# DADOS
# ---------------------------------------------------------------------------
ENTRIES = []

# ===========================================================================
# XBOX ORIGINAL — DASHBOARDS / LAUNCHERS
# Fontes: consolemods.org, xbins (distribution.xbins.org via archive.org),
#         GitHub (Rocky5, MakeMHz, Ryzee119, Team-Resurgent, OfficialTeamUIX)
# ===========================================================================
ENTRIES += [
    ("xbmc", "xbox", "XBMC (Xbox Media Center)", "Kodi (software)", 2003, "dashboard",
     ["Team XBMC"],
     "Media center e dashboard que viria a se tornar o Kodi; o software homebrew mais icônico do Xbox.",
     "https://github.com/xbmc/xbmc", "high"),
    ("xbmc4xbox", "xbox", "XBMC4Xbox", "XBMC4Xbox", 2010, "dashboard",
     ["Team XBMC4Xbox"],
     "Fork do XBMC mantido exclusivamente para o Xbox original depois que o projeto principal abandonou o console.",
     "https://github.com/xbmc4xbox", "high"),
    ("kodi4xbox", "xbox", "Kodi4Xbox", "XBMC4Xbox", None, "dashboard",
     ["Team XBMC4Xbox"],
     "Continuação moderna do XBMC4Xbox, com o nome e parte do código do Kodi.",
     "https://github.com/xbmc4xbox/kodi4xbox", "high"),
    ("xbmc4gamers", "xbox", "XBMC4Gamers", None, 2015, "dashboard",
     ["Rocky5"],
     "Distribuição do XBMC voltada a jogos, com skin própria e scripts Python para perfis e saves.",
     "https://github.com/Rocky5/XBMC4Gamers", "high"),
    ("xbmc-emustation", "xbox", "XBMC-Emustation", None, None, "dashboard",
     ["Rocky5"],
     "Front-end de emuladores construído sobre o XBMC, no estilo EmulationStation.",
     "https://github.com/Rocky5/XBMC-Emustation", "high"),
    ("unleashx", "xbox", "UnleashX", None, None, "dashboard",
     ["Team UnleashX"],
     "Dashboard leve e altamente configurável por XML, um dos mais usados em Xbox softmodado.",
     None, "high"),
    ("evolutionx", "xbox", "EvolutionX (EvoX)", None, None, "dashboard",
     ["Team Evolution-X"],
     "Dashboard clássico da cena, com gerenciador de arquivos, FTP e configuração de vídeo/rede.",
     None, "high"),
    ("avalaunch", "xbox", "Avalaunch", None, None, "dashboard",
     ["Team Avalaunch"],
     "Dashboard open source com forte suporte a rede, FTP e skins.",
     None, "high"),
    ("mediaxmenu", "xbox", "Media X Menu (MXM)", None, None, "dashboard",
     ["Ben Jeremy", "Lord_FF"],
     "Dashboard focado em apresentação visual de jogos e mídia, com suporte a temas.",
     None, "high"),
    ("nexgen", "xbox", "neXgen", None, None, "dashboard",
     ["HoRnEyDvL"],
     "Dashboard open source que imita o visual do dashboard oficial, com FTP embutido e scripts Lua.",
     "https://sourceforge.net/projects/nexgen", "high"),
    ("uix", "xbox", "UIX (User Interface X)", None, 2003, "dashboard",
     ["Team UIX"],
     "Modificação do próprio dashboard oficial da Microsoft, adicionando skins e recursos homebrew.",
     "https://github.com/OfficialTeamUIX", "high"),
    ("uix-lite", "xbox", "UIX Lite", None, None, "dashboard",
     ["Team UIX"],
     "Reimplementação moderna e enxuta do UIX sobre o dashboard oficial build 5960.",
     "https://github.com/OfficialTeamUIX/UIX-Lite", "high"),
    ("lithiumx", "xbox", "LithiumX", None, 2023, "dashboard",
     ["Ryzee119"],
     "Dashboard minimalista e rápido escrito com nxdk/LVGL, também compilável para PC.",
     "https://github.com/Ryzee119/LithiumX", "high"),
    ("nevolutionx", "xbox", "NevolutionX", None, 2019, "dashboard",
     ["dracc (Lucas Eriksson)", "abaire"],
     "Dashboard open source criado com o nxdk, com lançador de apps, temas e servidor FTP embutido.",
     "https://github.com/abaire/NevolutionX", "high"),
    ("dashloader", "xbox", "Dashloader", None, None, "dashboard",
     ["Rocky5"],
     "Lançador de dashboards configurável por INI, compatível com hardmod e softmod.",
     "https://github.com/Rocky5/Dashloader", "high"),
    ("prometheos", "xbox", "PrometheOS", None, None, "dashboard",
     ["Team Resurgent"],
     "Firmware/OS moderno para modchips do Xbox original, com interface gráfica e ferramentas integradas.",
     "https://github.com/Team-Resurgent/PrometheOS-Firmware", "high"),
    ("rdx", "xbox", "RDX", None, 2005, "dashboard",
     ["Team XOS"],
     "Dashboard-coleção que embute emuladores de SNES, NES, Master System e Mega Drive.",
     "https://github.com/risk510/TeamXOS-rdx", "high"),
    ("xbox-softmodding-tool", "xbox", "Rocky5's Xbox Softmodding Tool", None, None, "utility",
     ["Rocky5"],
     "Pacote de softmod que instala dashboard, backups de EEPROM e ferramentas num Xbox de fábrica.",
     "https://github.com/Rocky5/Xbox-Softmodding-Tool", "high"),
]

# ===========================================================================
# XBOX ORIGINAL — MÍDIA
# ===========================================================================
ENTRIES += [
    ("xbmp", "xbox", "Xbox Media Player (XBMP)", "Xbox Media Player", 2002, "media",
     ["Team XBMP"],
     "Primeiro tocador de mídia homebrew do Xbox; deu origem ao XBMC e, mais tarde, ao Kodi.",
     None, "high"),
    ("dvdx", "xbox", "DVDX", None, None, "media",
     ["Team Xecuter"],
     "Destrava a reprodução de DVD de vídeo sem o controle remoto/dongle oficial da Microsoft.",
     None, "high"),
]

# ===========================================================================
# XBOX ORIGINAL — EMULADORES
# Fontes: GameBrew (List of XBOX homebrew emulators), Emulation General Wiki,
#         xbins (apps/emulators), 1Emulation, SourceForge.
# Boa parte da lista vem da dupla XPort (autor original) + madmab (mantenedor).
# ===========================================================================
ENTRIES += [
    # --- Arcade ---
    ("mameox", "xbox", "MAMEoX", "MAME", None, "emulator", ["Erik Abair", "Team MAMEoX"],
     "O port histórico do MAME para o Xbox, base de quase todos os emuladores de arcade do console.",
     "https://sourceforge.net/projects/mameox/", "high"),
    ("mameoxtras", "xbox", "MAMEoXtras", "MAME", None, "emulator", ["Erik Abair", "opcode", "gamezfan", "BritneysPAIRS"],
     "Fork do MAMEoX mantido por anos pela comunidade, com centenas de drivers extras.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("coinops", "xbox", "CoinOPS", "MAME", 2003, "emulator", ["BritneysPAIRS"],
     "Compilação/front-end de arcade baseado em MAME, famoso (e polêmico) na cena do Xbox.",
     "https://consolemods.org/wiki/Xbox:CoinOPS", "high"),
    ("final-burn-legends", "xbox", "Final Burn Legends", None, None, "emulator", ["+T+", "destronger", "arcadez (gamezfan)"],
     "Port do Final Burn Alpha e do FBA-XXX Pro, cobrindo mais de 2700 jogos de arcade.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("final-burn-consoles", "xbox", "Final Burn Consoles", None, 2011, "emulator", ["+T+"],
     "Derivado do Final Burn Legends focado em consoles: Mega Drive, Neo Geo AES e CPS Changer.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("cpx3", "xbox", "CPX3", "CP System III", 2007, "emulator", ["ElSemi"],
     "Emulador de Capcom Play System 3 (Street Fighter III) para o Xbox.",
     "https://www.1emulation.com/forums/topic/23333-elsemis-cps3-cpx3-emulator-v10-released/", "high"),
    ("xraine", "xbox", "xRaine", None, 2011, "emulator", ["A600"],
     "Port do emulador de arcade Raine, de Antiriad e Emmanuel Anne.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("kixxx", "xbox", "KIxxx", None, 2006, "emulator", ["Team Logic-Sunrise", "SPPV"],
     "Emula o hardware de arcade Ultra 64 para rodar Killer Instinct 1 e 2.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("daphnex", "xbox", "DaphneX", None, 2003, "emulator", ["Kubik"],
     "Port do Daphne, emulador de arcades em LaserDisc como Dragon's Lair e Space Ace.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    # --- Neo Geo ---
    ("xneoraine", "xbox", "xNeoRaine", "Neo Geo CD", 2011, "emulator", ["A600"],
     "Port do NeoRaine para rodar jogos de Neo Geo CD no Xbox.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("neopopx", "xbox", "NeoPopX", "Neo Geo Pocket", None, "emulator", ["XPort", "madmab"],
     "Emulador de Neo Geo Pocket e Neo Geo Pocket Color.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    # --- Atari ---
    ("z26x", "xbox", "Z26X", "Atari 2600", None, "emulator", ["XPort", "madmab"],
     "Port do z26, emulador de Atari 2600.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("atari7800x", "xbox", "Atari7800X", "Atari 7800", None, "emulator", ["XPort", "madmab"],
     "Emulador de Atari 7800 derivado do núcleo do MESS.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("atarixlbox", "xbox", "AtariXLBox", "Atari 8-bit computers", None, "emulator", ["XPort", "madmab"],
     "Emulador dos computadores Atari 800/XL/XE e do console Atari 5200.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("mednafenx-lynx", "xbox", "MednafenX-Lynx", "Mednafen", None, "emulator", ["XPort", "madmab"],
     "Emulador de Atari Lynx baseado no núcleo do Mednafen.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("virtual-jaguarx", "xbox", "Virtual JaguarX", "Atari Jaguar", 2017, "emulator", ["HCF"],
     "Port do Virtual Jaguar, emulador de Atari Jaguar.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("winstonx", "xbox", "WinSTonX", "Atari ST", None, "emulator", ["XPort", "madmab"],
     "Port do WinSTon, emulador do computador Atari ST.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    # --- Sega ---
    ("neogenesis", "xbox", "NeoGenesis", "Sega Genesis", None, "emulator", ["XPort", "madmab"],
     "Emulador de Mega Drive, 32X e Sega CD que lê discos originais no drive do Xbox.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("neogensplusgx", "xbox", "NeoGensPlusGX", "Sega Genesis", None, "emulator", ["XtecuterX73", "madmab"],
     "Emulador multi-Sega baseado no Genesis Plus GX: Mega Drive, 32X, Sega CD, Master System, Game Gear e SG-1000.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("mekax", "xbox", "MekaX", "Master System", None, "emulator", ["XPort", "madmab"],
     "Port do MEKA: Master System, Game Gear, SG-1000, SC-3000 e Mark III.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("yabause-ce", "xbox", "Yabause CE", "Sega Saturn", 2013, "emulator", ["freakdave"],
     "Port comunitário do Yabause, emulador de Sega Saturn para o Xbox.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("softvmux", "xbox", "SoftVMUX", "Dreamcast", None, "emulator", ["XPort", "madmab"],
     "Emula o VMU (Visual Memory Unit) do Dreamcast, incluindo seus minijogos.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    # --- Nintendo ---
    ("fceultrax", "xbox", "FCEUltraX", "FCEUX", None, "emulator", ["XPort"],
     "Port do FCE Ultra, emulador de NES e Famicom Disk System.",
     None, "high"),
    ("nestopiax", "xbox", "NestopiaX", "Nestopia", None, "emulator", ["nes6502", "XtecuterX73"],
     "Port do Nestopia, considerado o emulador de NES mais preciso do Xbox.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("mednafenx-nes", "xbox", "MednafenX-NES", "Mednafen", None, "emulator", ["XPort", "madmab"],
     "Emulador de NES/FDS/VS UniSystem baseado no núcleo do Mednafen.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("snes9xbox", "xbox", "SNES9XBox", "Snes9x", None, "emulator", ["XPort", "madmab"],
     "Port do Snes9x, emulador de Super Nintendo.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("zsnexbox", "xbox", "ZsnexBox", "ZSNES", None, "emulator", ["nes6502"],
     "Port do ZSNES, por muitos anos o emulador de SNES mais popular do Xbox.",
     None, "medium"),
    ("surreal64", "xbox", "Surreal 64", "Nintendo 64", None, "emulator", ["Team Surreal"],
     "Primeiro emulador de Nintendo 64 do Xbox, combinando os núcleos 1964, Project64 e UltraHLE.",
     None, "high"),
    ("surreal64ce", "xbox", "Surreal64 CE", "Nintendo 64", None, "emulator", ["weinerschnitzel", "Ez0n3", "Joel Middendorf", "freakdave"],
     "Community Edition do Surreal 64, a versão mais avançada de emulação de N64 no Xbox.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("xboyadvance", "xbox", "XBoyAdvance", "VisualBoyAdvance", None, "emulator", ["XPort", "madmab"],
     "Emulador de Game Boy, Game Boy Color, Super Game Boy e Game Boy Advance.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("gbax", "xbox", "GBAx", "Game Boy Advance", 2002, "emulator", ["Anônimo"],
     "Um dos primeiros emuladores de Game Boy Advance lançados para o Xbox.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("virtualboyx", "xbox", "VirtualBoyX", None, None, "emulator", ["XPort", "madmab"],
     "Emulador do Nintendo Virtual Boy para o Xbox.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("pokemonminix", "xbox", "PokemonMiniX", None, None, "emulator", ["XPort", "madmab"],
     "Emulador do Pokémon Mini, o menor console da Nintendo.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("desmumex", "xbox", "DesmumeX", None, 2017, "emulator", ["HCF"],
     "Port do DeSmuME 0.9.11, emulador de Nintendo DS — extremamente lento no hardware do Xbox.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    # --- NEC / PC Engine ---
    ("mednafenx-pce", "xbox", "MednafenX-PCE", "Mednafen", None, "emulator", ["XPort", "madmab"],
     "Emulador de PC Engine/TurboGrafx-16, SuperGrafx e Arcade Card CD.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("neko-project2x", "xbox", "Neko Project2X", None, 2016, "emulator", ["HCF"],
     "Port do Neko Project II, emulador do computador NEC PC-98.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    # --- Outros consoles ---
    ("pcsxbox", "xbox", "PCSXbox", "PCSX-Reloaded", None, "emulator", ["XPort", "madmab"],
     "Port do PCSX, emulador de PlayStation 1 para o Xbox.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("pcsx-reloadedx", "xbox", "PCSX-ReloadedX", "PCSX-Reloaded", None, "emulator", ["freakdave"],
     "Reescrita moderna do emulador de PlayStation 1 no Xbox, baseada no PCSX-Reloaded.",
     "https://github.com/freakdave/PCSX-ReloadedX-Stable", "high"),
    ("adamx", "xbox", "AdamX", "ColecoVision", None, "emulator", ["XPort", "madmab"],
     "Emulador de ColecoVision e do computador Coleco Adam.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("odysseyx", "xbox", "OdysseyX", "Magnavox Odyssey 2", None, "emulator", ["XPort", "madmab"],
     "Emulador do Magnavox Odyssey² / Philips Videopac.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("blissx", "xbox", "BlissX", "Intellivision", None, "emulator", ["XPort", "madmab"],
     "Port do Bliss, emulador de Mattel Intellivision.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("messtrex", "xbox", "MessTrex", "Vectrex", None, "emulator", ["Chips", "madmab"],
     "Emulador do GCE Vectrex baseado no núcleo do MESS.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("xvectrex", "xbox", "XVectrex", "Vectrex", None, "emulator", ["Chips"],
     "Port do vecx, primeiro emulador de Vectrex do Xbox.",
     None, "medium"),
    ("3dox", "xbox", "3DOx", "3DO Interactive Multiplayer", 2011, "emulator", ["incrediclint"],
     "Emulador de 3DO baseado no FreeDO/4DO.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("supervisionx", "xbox", "SuperVisionX", None, None, "emulator", ["XPort", "madmab"],
     "Emulador do portátil Watara Supervision.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("wonderswanx", "xbox", "WonderSwanX", "WonderSwan", None, "emulator", ["XPort", "madmab"],
     "Emulador do portátil Bandai WonderSwan.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("madrigalx", "xbox", "MADrigalX", None, 2018, "emulator", ["HCF"],
     "Port dos simuladores de jogos eletrônicos LCD (Game & Watch) de Luca Antignano.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("epochx", "xbox", "EpochX", "Super Cassette Vision", None, "emulator", ["Comunidade Xbox-Scene"],
     "Emulador do Epoch Super Cassette Vision.",
     "https://www.1emulation.com/forums/topic/36500-epochx-v10-new-release/", "high"),
    ("uzeboxx", "xbox", "Uzeboxx", None, 2019, "emulator", ["HCF"],
     "Port do CUzeBox, emulador do console homebrew open source Uzebox.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("muchimex", "xbox", "MuchimeX", None, 2014, "emulator", ["HCF"],
     "Emula o SoC Sunplus SPG2XX usado em consoles plug-and-play chineses.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("messoxtras", "xbox", "MessoXtras", "Multi Emulator Super System", 2018, "emulator", ["HCF", "madmab"],
     "Port do MESS para o Xbox, cobrindo dezenas de sistemas obscuros.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("retroarch-xbox", "xbox", "RetroArch (Xbox)", "RetroArch", None, "emulator", ["Libretro"],
     "Front-end libretro com vários núcleos rodando no Xbox original.",
     "https://www.retroarch.com/", "high"),
    # --- Computadores ---
    ("winuaex", "xbox", "WinUAEX", "UAE (emulator)", None, "emulator", ["XPort", "madmab"],
     "Port do WinUAE, emulador de Commodore Amiga.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("vice64x", "xbox", "Vice64X", "Commodore 64", None, "emulator", ["XPort", "madmab"],
     "Port do VICE para emular o Commodore 64.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("vice20x", "xbox", "Vice20X", "Commodore VIC-20", None, "emulator", ["XPort", "madmab"],
     "Port do VICE para emular o Commodore VIC-20.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("vicepetx", "xbox", "VicePETX", "Commodore PET", None, "emulator", ["XPort", "madmab"],
     "Port do VICE para emular o Commodore PET.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("arnoldx", "xbox", "ArnoldX", "Amstrad CPC", None, "emulator", ["XPort", "madmab"],
     "Port do Arnold, emulador do computador Amstrad CPC.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("kegs-x", "xbox", "KEGS-X", "Apple IIGS", None, "emulator", ["XPort", "madmab"],
     "Port do KEGS, emulador de Apple IIgs/IIe/IIc.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("bluemsxbox", "xbox", "BlueMSXBox", "MSX", None, "emulator", ["XPort", "madmab"],
     "Port do blueMSX, emulador de MSX, MSX2 e MSX2+.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("didntxspectrum", "xbox", "DidntXSpectrum", "Fuse (emulator)", None, "emulator", ["XPort", "madmab"],
     "Emulador de ZX Spectrum derivado do Fuse.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("xzx81", "xbox", "Xzx81", "ZX81", None, "emulator", ["Comunidade Xbox-Scene"],
     "Emulador do Sinclair ZX81.",
     None, "medium"),
    ("x68000x", "xbox", "X68000X", "X68000", None, "emulator", ["XPort", "madmab"],
     "Emulador do computador Sharp X68000.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("samcoupex", "xbox", "SamCoupeX", "SAM Coupé", 2017, "emulator", ["HCF", "madmab"],
     "Emulador do computador britânico SAM Coupé.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("classic99x", "xbox", "Classic99x", "TI-99/4A", None, "emulator", ["XPort", "madmab"],
     "Port do Classic99, emulador do Texas Instruments TI-99/4A.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("chip8x", "xbox", "Chip8X", "CHIP-8", None, "emulator", ["XPort", "madmab"],
     "Interpretador de CHIP-8 e SuperCHIP-8 para o Xbox.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("xmac", "xbox", "XMac", "Mini vMac", None, "emulator", ["Comunidade Xbox-Scene"],
     "Port do Mini vMac, emulador do Macintosh Plus.",
     None, "medium"),
    ("xthom", "xbox", "XThom", None, None, "emulator", ["Comunidade Xbox-Scene"],
     "Emulador do computador francês Thomson TO7-70.",
     None, "medium"),
    ("bochs-xbox", "xbox", "Bochs (Xbox)", "Bochs", None, "emulator", ["XPort"],
     "Port do Bochs, emulador de PC x86 rodando dentro do Xbox.",
     None, "medium"),
    ("dosxbox", "xbox", "DOSXbox", "DOSBox", None, "emulator", ["XPort"],
     "Port do DOSBox para rodar jogos de MS-DOS no Xbox original.",
     None, "high"),
    ("scummvm-xbox", "xbox", "ScummVM (Xbox)", "ScummVM", None, "emulator", ["A600"],
     "Port do ScummVM, interpretador para aventuras point-and-click clássicas.",
     "https://www.gamebrew.org/wiki/List_of_XBOX_homebrew_emulators", "high"),
    ("sarienx", "xbox", "SarienX", None, None, "emulator", ["Comunidade Xbox-Scene"],
     "Interpretador AGI da Sierra, roda King's Quest 1-3 e Leisure Suit Larry 1.",
     None, "medium"),
    ("xmugen", "xbox", "XMugen", "Mugen (game engine)", None, "emulator", ["Comunidade Xbox-Scene"],
     "Distribuição Linux mínima que roda o motor de luta M.U.G.E.N no Xbox.",
     None, "medium"),
]

# ===========================================================================
# XBOX ORIGINAL — PORTS DE JOGOS
# Fontes: GameBrew (Category:XBOX Homebrews), xbins (games), XboxDev/nxdk wiki,
#         GitHub (Ryzee119, Team-Resurgent, XProger, MrMilenko, jroc-hb).
# ===========================================================================
ENTRIES += [
    ("doom-x", "xbox", "Doom-X", "Doom (1993 video game)", 2004, "port", ["Carcharius", "LikkleBaer", "Lantus"],
     "Port de Doom para o Xbox; precisa dos arquivos WAD originais do jogo.",
     None, "high"),
    ("doom-legacy-xbox", "xbox", "Doom Legacy (Xbox)", "Doom (1993 video game)", 2004, "port", ["Carcharius"],
     "Port do motor Doom Legacy, com multiplayer e suporte a mods.",
     None, "high"),
    ("odamex-xbox", "xbox", "OdameX", "Doom (1993 video game)", 2014, "port", ["Michael Wood (Hyper_Eye)"],
     "Port do Odamex, source port de Doom voltado a multiplayer online.",
     "https://odamex.net/", "high"),
    ("dc27-dooom", "xbox", "dc27-dooom", "Doom (1993 video game)", 2019, "port", ["Matt Borgerson"],
     "Doom baseado no Chocolate Doom feito com nxdk para o CTF da DEF CON 27.",
     "https://github.com/mborgerson/dc27-dooom", "high"),
    ("quakex", "xbox", "QuakeX", "Quake (video game)", 2004, "port", ["Lantus"],
     "Port de Quake para o Xbox, derivado do SDLQuake 1.09.",
     None, "high"),
    ("quake2x-le", "xbox", "Quake2X-LE", "Quake II", 2004, "port", ["Lantus"],
     "Port de Quake II para o Xbox, a partir do Quake2Forge.",
     None, "high"),
    ("quake3-xbox", "xbox", "Quake 3 (Xbox)", "Quake III Arena", 2005, "port", ["Carcharius"],
     "Port do motor de Quake III Arena, com single player e jogo em rede.",
     None, "high"),
    ("xduke", "xbox", "XDuke", "Duke Nukem 3D", 2006, "port", ["A600"],
     "Port de Duke Nukem 3D baseado no JFDuke3D.",
     None, "high"),
    ("xheretic", "xbox", "xHeretic", "Heretic (video game)", 2006, "port", ["A600"],
     "Port de Heretic para o Xbox.",
     None, "high"),
    ("xhexen", "xbox", "xHexen", "Hexen: Beyond Heretic", 2006, "port", ["A600"],
     "Port de Hexen: Beyond Heretic para o Xbox.",
     None, "high"),
    ("wolf3d-openxdk", "xbox", "Wolf3D OpenXDK Port", "Wolfenstein 3D", 2006, "port", ["th0mas"],
     "Port de Wolfenstein 3D feito com o OpenXDK, sem código do SDK oficial.",
     None, "high"),
    ("rottx", "xbox", "Rise of the Triad X (RottX)", "Rise of the Triad", 2003, "port", ["Lantus"],
     "Port de Rise of the Triad para o Xbox.",
     None, "high"),
    ("xdescent", "xbox", "xDescent", "Descent (video game)", 2006, "port", ["A600"],
     "Port de Descent baseado no D2X-Rebirth.",
     None, "high"),
    ("shadowx", "xbox", "ShadowX", "Shadow Warrior (1997 video game)", 2006, "port", ["A600"],
     "Port de Shadow Warrior baseado no JFShadowWarrior.",
     None, "high"),
    ("abusex", "xbox", "AbuseX", "Abuse (video game)", 2006, "port", ["XPort"],
     "Port do run-and-gun Abuse, a partir do Abuse-SDL.",
     None, "high"),
    ("open-transport-tycoon-xbox", "xbox", "Xbox Open Transport Tycoon", "OpenTTD", 2004, "port", ["HCl"],
     "Port do OpenTTD, recriação open source de Transport Tycoon Deluxe.",
     None, "high"),
    ("cavestoryx", "xbox", "CaveStoryX", "Cave Story", 2007, "port", ["XPort"],
     "Port de Cave Story, o clássico indie de Daisuke Amaya.",
     None, "high"),
    ("openlara-xbox", "xbox", "OpenLara (Xbox)", "Tomb Raider (1996 video game)", 2020, "port", ["XProger"],
     "Reimplementação open source do motor de Tomb Raider rodando no Xbox original.",
     "https://github.com/XProger/OpenLara", "high"),
    ("openbor-xbox", "xbox", "OpenBOR (Xbox)", "Beats of Rage", 2016, "port", ["A600", "madmab"],
     "Port do motor OpenBOR, que roda beat 'em ups criados pela comunidade.",
     None, "high"),
    ("beatsofragex", "xbox", "Beats of RageX", "Beats of Rage", 2006, "port", ["XPort"],
     "Port original do Beats of Rage, beat 'em up gratuito da Senile Team.",
     None, "high"),
    ("xsorr", "xbox", "XSorR (Streets of Rage Remake)", "Streets of Rage", 2011, "port", ["A600"],
     "Port do interpretador BennuGD que roda o fangame Streets of Rage Remake.",
     None, "medium"),
    ("exultx", "xbox", "ExultX", "Ultima VII: The Black Gate", 2004, "port", ["Stealth"],
     "Port do Exult, motor open source para Ultima VII.",
     None, "high"),
    ("xurquan", "xbox", "xUrQuan", "The Ur-Quan Masters", 2011, "port", ["A600"],
     "Port do The Ur-Quan Masters, versão livre de Star Control II.",
     None, "high"),
    ("rawx", "xbox", "RawX", "Another World (video game)", 2004, "port", ["Lantus"],
     "Port do motor rawgl, que roda Another World (Out of This World).",
     None, "high"),
    ("reminiscencex", "xbox", "ReminiscenceX", "Flashback (1992 video game)", 2005, "port", ["Lantus"],
     "Port do REminiscence, reimplementação do motor de Flashback.",
     None, "high"),
    ("xrick", "xbox", "xRick", "Rick Dangerous", 2004, "port", ["Lantus"],
     "Port do xrick, clone open source de Rick Dangerous.",
     None, "high"),
    ("avp-xbox", "xbox", "Aliens Vs. Predator (Xbox)", "Aliens versus Predator (1999 video game)", 2009, "port", ["SirLemonhead"],
     "Port não oficial do Aliens versus Predator Gold Edition de PC.",
     None, "medium"),
    ("sdlpopx", "xbox", "SDLPoPX", "Prince of Persia (1989 video game)", None, "port", ["Ryzee119"],
     "Port de Prince of Persia (1989) via SDLPoP.",
     "https://github.com/Ryzee119/SDLPoP", "high"),
    ("omnispeakx", "xbox", "omnispeakX", "Commander Keen", None, "port", ["Ryzee119"],
     "Reimplementação open source de Commander Keen in Goodbye, Galaxy! para o Xbox.",
     "https://github.com/Ryzee119/omnispeak", "high"),
    ("opentyrianx", "xbox", "OpenTyrianX", None, 2019, "port", ["Neobomb", "Ryzee119"],
     "Port do OpenTyrian, versão open source do shoot 'em up Tyrian.",
     "https://github.com/Ryzee119/opentyrianX", "high"),
    ("cosmo-enginex", "xbox", "cosmo-engineX", None, None, "port", ["Ryzee119"],
     "Motor reescrito de Cosmo's Cosmic Adventure rodando no Xbox original.",
     "https://github.com/Ryzee119/cosmo-engineX", "high"),
    ("raptor-xbox", "xbox", "Raptor: Call of the Shadows (Xbox)", "Raptor: Call of the Shadows", 2025, "port", ["RetroGamer02"],
     "Port do shoot 'em up Raptor a partir do código reconstruído por engenharia reversa.",
     "https://github.com/RetroGamer02/raptor-consoles", "high"),
    ("fallout1-ce-xbox", "xbox", "Fallout CE (Xbox)", "Fallout (video game)", None, "port", ["jroc-hb"],
     "Port de Fallout (1997) usando o Fallout Community Edition.",
     "https://github.com/jroc-hb/fallout1-ce-xbox", "high"),
    ("fallout2-ce-xbox", "xbox", "Fallout 2 CE (Xbox)", "Fallout 2", None, "port", ["MrMilenko"],
     "Port de Fallout 2 usando o Fallout2 Community Edition.",
     "https://github.com/MrMilenko/fallout2-ce", "high"),
    ("hodex", "xbox", "HODEX", None, 2020, "port", ["MVG", "Lantus", "Rocky5"],
     "Port do motor HODE, que roda o jogo de plataforma Heart of Darkness.",
     None, "high"),
    ("mario-kart-64-x", "xbox", "Mario Kart 64 X", "Mario Kart 64", None, "port", ["Team Resurgent"],
     "Port de Mario Kart 64 para o Xbox original a partir da descompilação do jogo de N64.",
     "https://github.com/Team-Resurgent/Mario-Kart-64-X", "high"),
    ("zelda-alttp-x", "xbox", "Zelda: A Link to the Past X", "The Legend of Zelda: A Link to the Past", None, "port", ["Team Resurgent"],
     "Port de The Legend of Zelda: A Link to the Past para o Xbox usando o RXDK.",
     "https://github.com/Team-Resurgent/Zelda-A-Link-To-The-Past-X", "high"),
    ("super-mario-world-x", "xbox", "Super Mario World X", "Super Mario World", None, "port", ["Team Resurgent"],
     "Port de Super Mario World, Super Mario Bros. e Lost Levels para o Xbox original.",
     "https://github.com/Team-Resurgent/Super-Mario-World-X", "high"),
    ("megamanx-x", "xbox", "Mega Man X X", "Mega Man X (video game)", None, "port", ["Team Resurgent"],
     "Port de Mega Man X para o Xbox original usando o RXDK.",
     "https://github.com/Team-Resurgent/MegaManX-X", "high"),
    ("celeste-rxdk", "xbox", "Celeste Classic (RXDK)", "Celeste (video game)", None, "port", ["Team Resurgent"],
     "Port do Celeste Classic (versão PICO-8) para o Xbox original.",
     "https://github.com/Team-Resurgent/Celeste-RXDK", "high"),
    ("super-mario-war-xbox", "xbox", "Super Mario War (Xbox)", None, None, "port", ["Comunidade Xbox-Scene"],
     "Port do Super Mario War, jogo de arena multiplayer feito por fãs.",
     None, "high"),
    ("stepmaniax", "xbox", "StepmaniaX", "StepMania", None, "port", ["XPort"],
     "Port do StepMania, jogo de dança open source, com suporte a tapetes USB.",
     None, "high"),
    ("zelda-roth-xbox", "xbox", "Zelda: Return of the Hylian (Xbox)", None, 2011, "port", ["Neobomb"],
     "Port de um fangame francês de Zelda feito com Solarus.",
     None, "medium"),
    ("flycast-x", "xbox", "Flycast-X", "Dreamcast", None, "emulator", ["Team Resurgent"],
     "Prova de conceito de port do emulador de Dreamcast Flycast usando o RXDK.",
     "https://github.com/Team-Resurgent/Flycast-X", "high"),
]

# ===========================================================================
# XBOX ORIGINAL — JOGOS HOMEBREW AUTORAIS
# Fontes: GameBrew (Category:XBOX Homebrews), xbins (Console Based Applications/games)
# ===========================================================================
ENTRIES += [
    ("arcadian-tactics", "xbox", "Arcadian Tactics", None, 2012, "game", ["HCF"],
     "Jogo de estratégia por turnos autoral, com participações de personagens clássicos de videogame.",
     None, "medium"),
    ("magnetron", "xbox", "MagneTron", None, 2009, "game", ["Steven De Toni"],
     "Jogo de arcade autoral, rápido e baseado em magnetismo.",
     None, "medium"),
    ("xbomberbox", "xbox", "XBomberbox", None, 2003, "game", ["Marcelpopo"],
     "Jogo multiplayer autoral inspirado em Bomberman, um dos homebrew mais jogados do Xbox.",
     None, "medium"),
    ("x-pong", "xbox", "X-Pong", None, 2002, "game", ["XL Productions"],
     "Pong autoral para dois jogadores, demonstração inicial da cena homebrew.",
     None, "medium"),
    ("xskull", "xbox", "Skull (xSKULL)", None, 2013, "game", ["Diogo Lapa (GECA Soft)"],
     "Jogo de plataforma autoral desenvolvido para o Xbox original.",
     None, "medium"),
    ("star-wars-xbox-hb", "xbox", "Star Wars: A New Hope for Homebrew", None, 2004, "game", ["SHiZNO", "PeteGabe"],
     "Shooter 3D autoral com tema de Star Wars, feito por fãs.",
     None, "medium"),
    ("vortexion-xbox", "xbox", "Vortexion (Xbox)", None, None, "game", ["GamingNJncos"],
     "Port homebrew do shoot 'em up Vortexion feito com o nxdk.",
     "https://github.com/GamingNJncos/XboxPort_vortexion", "high"),
]

# ===========================================================================
# XBOX ORIGINAL — UTILITÁRIOS, BIOS, SOFTMOD, LINUX E FERRAMENTAS DE DEV
# ===========================================================================
ENTRIES += [
    ("configmagic", "xbox", "ConfigMagic", None, None, "utility", ["Team Assembly"],
     "Editor de EEPROM que lê/grava a chave do HD, região de vídeo e número de série do console.",
     None, "high"),
    ("chimp", "xbox", "Chimp", None, None, "utility", ["Comunidade Xbox-Scene"],
     "Ferramenta que clona e formata o HD do Xbox direto no console, sem PC.",
     "https://github.com/Rocky5/Chimp261812", "high"),
    ("xbpartitioner", "xbox", "XBPartitioner", None, None, "utility", ["opcow"],
     "Reparticiona e formata o HD do Xbox, liberando espaço de discos grandes.",
     "https://github.com/opcow/XBpartitioner", "high"),
    ("slayers-auto-installer", "xbox", "Slayer's EvoX Auto-Installer", None, None, "utility", ["SlaYer", "hal9000"],
     "Disco de instalação automática que particiona o HD e instala dashboard, XBMP e utilitários.",
     "https://archive.org/details/xbox-slayers", "high"),
    ("hexen-toolkit", "xbox", "HeXEn", None, None, "utility", ["Heimdall"],
     "Disco-ferramenta anual da cena, com flash de BIOS, construção de HD e instalação de dashboards.",
     "https://archive.org/details/hexen2018", "high"),
    ("endgame-exploit", "xbox", "ENDGAME", None, 2024, "utility", ["Markus Gaasedelen", "shutterbug2000", "xbox7887"],
     "Exploit do dashboard que roda um XBE assinado direto de um cartão de memória, sem leitor de DVD.",
     "https://github.com/XboxDev/endgame-exploit", "high"),
    ("dvd2xbox", "xbox", "DVD2Xbox", None, None, "utility", ["WiSo"],
     "Copia DVDs e CDs para o HD do Xbox, FTP ou SMB, com patch automático de FATX.",
     "https://archive.org/details/dvd2xbox-0.6.1", "high"),
    ("qwix", "xbox", "Qwix", None, None, "utility", ["Team Avalaunch"],
     "Ferramenta de PC que cria imagens XISO e gerencia transferências para o console.",
     "https://archive.org/details/Qwix.7z", "high"),
    ("extract-xiso", "xbox", "extract-xiso", None, None, "utility", ["XboxDev"],
     "Cria e extrai imagens XDVDFS (XISO) de discos do Xbox.",
     "https://github.com/XboxDev/extract-xiso", "high"),
    ("fatx-lib", "xbox", "fatx (biblioteca e GUI)", None, 2015, "utility", ["Matt Borgerson", "abaire"],
     "Biblioteca multiplataforma, driver FUSE e explorador gráfico do sistema de arquivos FATX.",
     "https://github.com/mborgerson/fatx", "high"),
    ("xdvdfs", "xbox", "xdvdfs", None, 2025, "utility", ["Ryzee119"],
     "Biblioteca e utilitário para o sistema de arquivos de disco XDVDFS do Xbox.",
     "https://github.com/Ryzee119/xdvdfs", "high"),
    ("repackinator", "xbox", "Repackinator", None, None, "utility", ["Team Resurgent", "Team Cerbios"],
     "Reempacota, divide e comprime dumps de ISO do Xbox, incluindo o formato CCI do Cerbios.",
     "https://github.com/Team-Resurgent/Repackinator", "high"),
    ("xboxtoolkit", "xbox", "XboxToolkit", None, None, "utility", ["Team Resurgent"],
     "Conjunto de ferramentas .NET para manipular arquivos ISO, XBE e XEX.",
     "https://github.com/Team-Resurgent/XboxToolkit", "high"),
    ("cromwell", "xbox", "Cromwell", "Xbox Linux", 2002, "utility", ["Xbox Linux Project", "XboxDev"],
     "BIOS open source e legal, sem código da Microsoft, criada para dar boot em Linux no Xbox.",
     "https://github.com/XboxDev/cromwell", "high"),
    ("cerbios", "xbox", "Cerbios", None, None, "utility", ["Team Cerbios"],
     "BIOS customizada moderna, híbrida retail/debug, com boot de ISO e suporte a HDs grandes.",
     "https://github.com/Cerbios/Cerbios-Xbox", "high"),
    ("cerbiostool", "xbox", "CerbiosTool", None, None, "utility", ["Team Resurgent"],
     "Ferramenta de PC para configurar e personalizar a BIOS Cerbios.",
     "https://github.com/Team-Resurgent/CerbiosTool", "high"),
    ("evox-bios", "xbox", "EvoX BIOS", None, None, "utility", ["Team Evolution-X"],
     "BIOS customizada clássica da cena, com desbloqueio de região e suporte a HDs maiores.",
     None, "high"),
    ("xenium-os", "xbox", "Xenium OS", None, None, "utility", ["Team Xecuter"],
     "Firmware do modchip Xenium, com seleção de bancos de BIOS e ferramentas embutidas.",
     None, "high"),
    ("openxenium", "xbox", "OpenXenium", None, 2019, "utility", ["Ryzee119"],
     "Recriação open source do CPLD do modchip Xenium para o Xbox original.",
     "https://github.com/Ryzee119/OpenXenium", "high"),
    ("modxo", "xbox", "Modxo", None, 2024, "utility", ["Team Resurgent"],
     "Firmware de modchip open source baseado no microcontrolador RP2040.",
     "https://github.com/Team-Resurgent/Modxo", "high"),
    ("xboxeepromeditor", "xbox", "XboxEepromEditor", None, None, "utility", ["Ernegien"],
     "Editor moderno de EEPROM do Xbox para PC.",
     "https://github.com/Ernegien/XboxEepromEditor", "high"),
    ("piprom", "xbox", "PiPROM", None, 2015, "utility", ["grimdoomer"],
     "Lê e grava a EEPROM do Xbox usando um Raspberry Pi.",
     "https://github.com/grimdoomer/PiPROM", "high"),
    ("nxdk", "xbox", "nxdk", None, None, "utility", ["XboxDev"],
     "SDK open source e multiplataforma que substitui o XDK oficial no desenvolvimento homebrew.",
     "https://github.com/XboxDev/nxdk", "high"),
    ("openxdk", "xbox", "OpenXDK", None, None, "utility", ["XboxDev"],
     "Primeiro SDK livre para o Xbox original, antecessor do nxdk.",
     "https://github.com/XboxDev/OpenXDK", "high"),
    ("ghidra-xbe", "xbox", "ghidra-xbe", None, 2020, "utility", ["XboxDev"],
     "Extensão do Ghidra que carrega executáveis XBE para engenharia reversa.",
     "https://github.com/XboxDev/ghidra-xbe", "high"),
    ("pyxbe", "xbox", "pyxbe", None, 2020, "utility", ["Matt Borgerson"],
     "Biblioteca Python para ler e analisar arquivos XBE.",
     "https://github.com/mborgerson/pyxbe", "high"),
    ("xbedump", "xbox", "xbedump", None, None, "utility", ["XboxDev"],
     "Mostra o cabeçalho e assina executáveis XBE do Xbox original.",
     "https://github.com/XboxDev/xbedump", "high"),
    ("viridix", "xbox", "ViridiX", None, None, "utility", ["XboxDev"],
     "Suíte de comunicação e depuração remota com o Xbox original.",
     "https://github.com/XboxDev/ViridiX", "high"),
    ("nv2a-trace", "xbox", "nv2a-trace", None, None, "utility", ["XboxDev"],
     "Ferramenta de trace da GPU NV2A do Xbox, no estilo apitrace.",
     "https://github.com/XboxDev/nv2a-trace", "high"),
    ("insignia", "xbox", "Insignia", "Insignia (Xbox)", 2022, "utility", ["Luke Usher", "Billy"],
     "Substituto comunitário do Xbox Live original, devolvendo o multiplayer online ao console.",
     "https://insignia.live/", "high"),
    ("xblunblock", "xbox", "xblunblock", None, 2021, "utility", ["Insignia"],
     "Desativa na memória o bloqueio de Xbox Live da BIOS para permitir conexão ao Insignia.",
     "https://github.com/insignia-live/xblunblock", "high"),
    ("xlink-kai", "xbox", "XLink Kai", "XLink Kai", 2003, "utility", ["Team XLink"],
     "Tunelamento de LAN pela internet, permitindo System Link entre consoles distantes.",
     "https://www.teamxlink.co.uk/", "high"),
    ("xbox-linux", "xbox", "Xbox Linux", "Xbox Linux", 2002, "utility", ["Xbox Linux Project"],
     "Projeto que portou o Linux para o Xbox original, usando a BIOS Cromwell ou exploits de save.",
     "https://sourceforge.net/projects/xbox-linux/", "high"),
    ("gentoox", "xbox", "Gentoox", "Xbox Linux", None, "utility", ["Projeto Gentoox"],
     "Distribuição Linux baseada em Gentoo feita sob medida para o Xbox original.",
     None, "high"),
    ("xebian", "xbox", "Xebian (Ed's Debian)", "Xbox Linux", None, "utility", ["Ed"],
     "Distribuição Linux baseada em Debian para o Xbox, instalável no HD ou em live CD.",
     "https://github.com/xbox-linux/debian", "high"),
    ("hawk-xblc", "xbox", "hawk", None, 2024, "utility", ["Ryzee119"],
     "Recriação open source do Xbox Live Communicator, o headset de voz do Xbox original.",
     "https://github.com/Ryzee119/hawk", "high"),
    ("ogx360", "xbox", "ogx360", None, None, "utility", ["Ryzee119"],
     "Adaptador que permite usar controles USB modernos (XInput) no Xbox original.",
     "https://github.com/Ryzee119/ogx360", "high"),
    ("xbox-hd-plus-app", "xbox", "Xbox HD+ App", None, None, "utility", ["MakeMHz"],
     "Aplicativo homebrew que controla o mod de vídeo digital Xbox HD+.",
     "https://github.com/MakeMHz/xbox-hd-plus-app", "high"),
    ("project-stellar", "xbox", "Project Stellar (StellarOS)", None, None, "utility", ["MakeMHz"],
     "Add-on moderno para o Xbox original com BIOS reimplementada e ferramentas próprias.",
     "https://github.com/MakeMHz/project-stellar", "high"),
    ("xbdstats", "xbox", "xbdStats", None, None, "utility", ["Rocky5"],
     "Envia ao Discord o status de Rich Presence do que está rodando no Xbox original.",
     "https://github.com/Rocky5/xbdStats", "high"),
]

# ===========================================================================
# XBOX 360 (JTAG/RGH) — DASHBOARDS E LANÇADORES
# Fontes: repositório oficial da Homebrew Store da ConsoleMods.org,
#         free60.org / Free60Project no GitHub, consolemods.org.
# ===========================================================================
ENTRIES += [
    ("xexmenu", "x360", "XeXMenu", None, None, "dashboard", ["Team XeDev"],
     "Primeiro dashboard homebrew popular do Xbox 360: gerenciador de arquivos, FTP e lançador de XEX.",
     None, "high"),
    ("freestyle-dash-3", "x360", "Freestyle Dash 3 (FSD3)", None, None, "dashboard", ["Team FSD"],
     "Dashboard alternativo altamente personalizável, com capas de jogos, skins e lançamento de homebrew.",
     None, "high"),
    ("freestyle-dash-2", "x360", "Freestyle Dash 2", None, None, "dashboard", ["Team FSD"],
     "Versão anterior do Freestyle Dash, ainda usada em consoles com NAND pequena.",
     None, "high"),
    ("aurora-dash", "x360", "Aurora", None, 2015, "dashboard", ["Phoenix Team"],
     "Dashboard moderno em coverflow, sucessor do Freestyle Dash e ainda mantido pela comunidade.",
     None, "high"),
    ("emerald-dash", "x360", "Emerald Dash", None, None, "dashboard", ["Ced2911"],
     "Dashboard open source para Xbox 360 modificado.",
     None, "high"),
    ("ingeniuox", "x360", "IngeniouX", None, None, "dashboard", ["Ski-lleR"],
     "Dashboard alternativo do início da cena JTAG, descontinuado na beta 3.",
     None, "high"),
    ("xexdash", "x360", "XexDash", None, None, "dashboard", ["JS-TEAM"],
     "Dashboard enxuto para lançar XEX; não confundir com o XeXMenu.",
     None, "high"),
    ("xexloader", "x360", "XeXLoader", None, None, "dashboard", ["FreeXeX"],
     "Primeiro menu público capaz de carregar executáveis XEX no Xbox 360.",
     None, "high"),
    ("viper360", "x360", "Viper360", None, None, "dashboard", ["Anônimo"],
     "Dashboard alternativo com uma única versão lançada.",
     None, "high"),
    ("xenu-dash", "x360", "Xenu", None, None, "dashboard", ["Diggs"],
     "Dashboard open source baseado em libXenon, instalado a partir de um pendrive.",
     None, "high"),
    ("xmenu-libxenon", "x360", "XMENU", None, None, "dashboard", ["cpasjuste"],
     "Lançador simples de arquivos ELF feito com libXenon, com fundos personalizáveis.",
     "https://free60.org/", "high"),
    ("xemini", "x360", "Xemini", None, None, "dashboard", ["Hwilliams8548"],
     "Dashboard e lançador de ELF open source baseado em libXenon.",
     "https://github.com/Hwilliams8548/Xemini", "high"),
]

# ===========================================================================
# XBOX 360 — EMULADORES
# ===========================================================================
ENTRIES += [
    ("retroarch-360", "x360", "RetroArch 360", "RetroArch", 2014, "emulator", ["Libretro"],
     "Front-end libretro oficial para Xbox 360, com dezenas de núcleos de emulação.",
     "https://www.retroarch.com/", "high"),
    ("retroarch-360-v3", "x360", "RetroArch 360 (Unofficial V3)", "RetroArch", None, "emulator", ["cmkn1983"],
     "Port não oficial do RetroArch 0.9.8 para Xbox 360.",
     None, "high"),
    ("3dox-360", "x360", "3DOx 360", "3DO Interactive Multiplayer", None, "emulator", ["Freedo Team"],
     "Emulador de 3DO no Xbox 360, baseado no FreeDO/FourDO.",
     None, "high"),
    ("amiga360", "x360", "Amiga360", "UAE (emulator)", None, "emulator", ["Lantus"],
     "Port do P-UAE 2.3.3, emulador de Commodore Amiga para Xbox 360.",
     None, "high"),
    ("cpx3-360", "x360", "CPx3 (CPS-3)", "CP System III", None, "emulator", ["ElSemi"],
     "Emulador de Capcom Play System 3 para Xbox 360.",
     None, "high"),
    ("dosxbox360", "x360", "DOSXbox360", "DOSBox", None, "emulator", ["Lantus"],
     "Port do DOSBox 0.74 para Xbox 360, melhorando a versão da Team XeLove.",
     None, "high"),
    ("dosbox-360-xelove", "x360", "DOSBox (Team XeLove)", "DOSBox", None, "emulator", ["Team XeLove"],
     "Primeiro port do DOSBox para Xbox 360.",
     None, "high"),
    ("xeboyadvance", "x360", "XeBoyAdvance", "VisualBoyAdvance", None, "emulator", ["Team XeLove"],
     "Emulador de Game Boy, Game Boy Color e Game Boy Advance baseado no VisualBoyAdvance.",
     None, "high"),
    ("vba360", "x360", "VBA360 (Visual Boy Advance 360)", "VisualBoyAdvance", None, "emulator", ["Comunidade libXenon"],
     "Emulador de GB/GBC/GBA para Xbox 360, derivado do VBA-M.",
     "https://github.com/frankischilling/vba360-enhanced", "high"),
    ("mame360", "x360", "MAME 360 (MAME 0.72)", "MAME", None, "emulator", ["Lantus", "Arcadez"],
     "Port do MAME 0.72 para Xbox 360, com suporte a quatro jogadores e cheats.",
     "https://github.com/mLoaDs/MAME360", "high"),
    ("fbneo-360", "x360", "FBNeo 360", None, None, "emulator", ["Team FBNeo"],
     "Port do FinalBurn Neo para Xbox 360, com ampla compatibilidade de arcade.",
     None, "high"),
    ("fbanext-360", "x360", "FBANext 360", None, None, "emulator", ["Lantus", "MagicSeb"],
     "Port do Final Burn Alpha para Xbox 360: CPS-1/2/3, Neo Geo, Cave, Toaplan e Psikyo.",
     "https://github.com/mLoaDs/FBANext360", "high"),
    ("dson360", "x360", "DSon360", None, None, "emulator", ["Yoshihiro"],
     "Port do DeSmuME, emulador experimental de Nintendo DS para Xbox 360.",
     None, "high"),
    ("fce360", "x360", "FCE360", "FCEUX", None, "emulator", ["Ced2911"],
     "Port do FCEUX, emulador de NES para Xbox 360.",
     "https://github.com/frankischilling/fce360-enhanced", "high"),
    ("pce360", "x360", "PCE360", "TurboGrafx-16", None, "emulator", ["Yoshihiro"],
     "Emulador nativo de PC Engine/TurboGrafx-16 com suporte a HuCard e CD.",
     None, "high"),
    ("freepsx", "x360", "FreePSX", "PlayStation (console)", None, "emulator", ["Logic Sunrise Team"],
     "Emulador nativo de PlayStation 1 escrito para o Xbox 360.",
     None, "high"),
    ("pcsxr-360", "x360", "PCSXR-360", "PCSX-Reloaded", None, "emulator", ["Ced2911"],
     "Port do PCSX-Reloaded, emulador de PlayStation 1 para Xbox 360.",
     None, "high"),
    ("genesis360", "x360", "Genesis360", "Sega Genesis", None, "emulator", ["Yoshihiro"],
     "Port do Genesis Plus GX para Xbox 360.",
     None, "high"),
    ("genesis-plus-360", "x360", "Sega Genesis Plus 360", "Sega Genesis", None, "emulator", ["Ced2911"],
     "Port do Genesis Plus GX: Mega Drive, Master System e Game Gear.",
     None, "high"),
    ("sms360", "x360", "SMS360", "Master System", None, "emulator", ["Yoshihiro"],
     "Emulador de Sega Master System e Game Gear para Xbox 360.",
     None, "high"),
    ("smsplus-360", "x360", "SMS Plus 360", "Master System", None, "emulator", ["Ced2911"],
     "Port do SMS Plus, emulador de Master System e Game Gear via libXenon.",
     None, "high"),
    ("snes360", "x360", "Snes360", "Snes9x", None, "emulator", ["Comunidade libXenon"],
     "Primeiro emulador de Super Nintendo do Xbox 360, baseado no Snes9x GX.",
     "https://github.com/frankischilling/snes360-enhanced", "high"),
    ("snes9x-gx-xenon", "x360", "Snes9x GX (Xenon)", "Snes9x", None, "emulator", ["tmbinc"],
     "Port do Snes9x GX para libXenon, executado a partir de um pendrive.",
     None, "high"),
    ("scummvm-360", "x360", "ScummVM 360", "ScummVM", None, "emulator", ["A600"],
     "Port do ScummVM 1.4.1 para Xbox 360, para aventuras point-and-click.",
     None, "high"),
    ("vecx-360", "x360", "Vecx-360", "Vectrex", None, "emulator", ["chemone", "Mac1512"],
     "Port do Vecx, emulador do console vetorial Vectrex.",
     "https://github.com/chemone/Vecx-360", "high"),
    ("virtual-jaguarx-360", "x360", "Virtual JaguarX 360", "Atari Jaguar", None, "emulator", ["MagicSeb"],
     "Port do Virtual Jaguar 1.0.5 para Xbox 360.",
     None, "high"),
    ("ppsspp-360", "x360", "PPSSPP 360", "PlayStation Portable", None, "emulator", ["Ced2911"],
     "Port experimental do PPSSPP, emulador de PSP, para Xbox 360.",
     None, "high"),
    ("mupen64-360", "x360", "Mupen64-360", "Mupen64Plus", None, "emulator", ["GliGli"],
     "Emulador de Nintendo 64 para Xbox 360, derivado do Wii64/Mupen64.",
     "https://github.com/gligli/mupen64-360", "high"),
    ("nulldc-360", "x360", "NullDC 360", "Dreamcast", None, "emulator", ["GliGli"],
     "Port do NullDC, emulador de Sega Dreamcast, rodando via libXenon.",
     None, "high"),
]

# ===========================================================================
# XBOX 360 — PORTS E JOGOS HOMEBREW
# ===========================================================================
ENTRIES += [
    ("sdl-quake-360", "x360", "SDL-Quake 360", "Quake (video game)", None, "port", ["Lantus"],
     "Port de Quake feito com libXenon e SDL, vitrine do desenvolvimento homebrew no 360.",
     None, "high"),
    ("quake3-360", "x360", "Quake3-360", "Quake III Arena", None, "port", ["Ced2911", "sk1080", "Razkar"],
     "Port de Quake III Arena para Xbox 360; exige os arquivos do jogo original.",
     None, "high"),
    ("openbor-360", "x360", "OpenBOR 360", "Beats of Rage", None, "port", ["Senile Team", "Lantus"],
     "Port do motor OpenBOR de beat 'em up para Xbox 360.",
     "https://github.com/mLoaDs/OpenBOR360", "high"),
    ("beats-of-rage-360", "x360", "Beats of Rage 360", "Beats of Rage", None, "port", ["Senile Team"],
     "Port do beat 'em up gratuito Beats of Rage para Xbox 360.",
     None, "high"),
    ("exult-360", "x360", "Exult 360", "Ultima VII: The Black Gate", None, "port", ["Exult Team"],
     "Port do Exult, recriação open source do motor de Ultima VII.",
     "http://exult.sourceforge.net/", "high"),
    ("openjazz360", "x360", "OpenJazz360", "Jazz Jackrabbit", None, "port", ["LoveMHz"],
     "Port do OpenJazz, motor livre para Jazz Jackrabbit da Epic MegaGames.",
     None, "high"),
    ("rawx-360", "x360", "RAWx 360", "Another World (video game)", None, "port", ["MagicSeb"],
     "Port do motor de Another World (Out of This World) para Xbox 360.",
     None, "high"),
    ("reminiscene360", "x360", "Reminiscene360", "Flashback (1992 video game)", None, "port", ["MagicSeb"],
     "Port do REminiscence, motor livre de Flashback, para Xbox 360.",
     None, "high"),
    ("rick360", "x360", "Rick360", "Rick Dangerous", None, "port", ["MagicSeb"],
     "Port do xrick, clone de Rick Dangerous, para Xbox 360.",
     None, "high"),
    ("xbermuda360", "x360", "xBermuda360", None, None, "port", ["A600"],
     "Port do motor do jogo de aventura Bermuda Syndrome para Xbox 360.",
     None, "high"),
    ("super-mario-war-360", "x360", "Super Mario War 360", None, None, "port", ["Cancerous1", "Team XeLove"],
     "Port do Super Mario War, arena multiplayer feita por fãs.",
     None, "high"),
    ("flappybird-360", "x360", "FlappyBird 360", None, None, "port", ["joojoooo"],
     "Port do Flappy Bird para Xbox 360 modificado.",
     None, "high"),
    ("tank360", "x360", "Tank360", None, None, "game", ["JQE"],
     "Jogo autoral de tanques feito para Xbox 360 com libXenon.",
     None, "high"),
    ("tanks-360", "x360", "Tanks 360", None, None, "game", ["Comunidade libXenon"],
     "Jogo homebrew de combate de tanques distribuído pelo Free60.",
     "https://free60.org/", "high"),
    ("pong-360", "x360", "Pong (libXenon)", None, None, "game", ["Comunidade libXenon"],
     "Demo homebrew de Pong, um dos primeiros programas rodados via libXenon.",
     "https://free60.org/", "high"),
    ("fursan-al-aqsa", "x360", "Fursan al-Aqsa: The Knights of the Al-Aqsa Mosque", None, None, "game", ["Nidal Nijm"],
     "FPS autoral completo lançado como homebrew para Xbox 360 modificado.",
     None, "high"),
    ("quadcarnage", "x360", "QuadCarnage", None, None, "game", ["Jared Levi"],
     "Shooter multiplayer minimalista e caótico feito para Xbox 360.",
     None, "high"),
    ("wowjay", "x360", "WowJay", None, None, "game", ["Jared Levi"],
     "Jogo de arcade retrô autoral para Xbox 360.",
     None, "high"),
    ("nestbound", "x360", "NestBound", None, None, "game", ["Jared Levi"],
     "Jogo autoral em que se desenha uma linha para guiar um pássaro até a vitória.",
     None, "high"),
    ("pacman-colors", "x360", "PACMAN COLORS", None, None, "game", ["Gunz4Hire"],
     "Clone autoral de Pac-Man com estética neon e grade que aumenta a dificuldade.",
     None, "high"),
    ("paddle-meyhem", "x360", "Paddle Meyhem", None, None, "game", ["Gunz4Hire"],
     "Releitura autoral de Pong com gráficos atualizados e luzes dançantes.",
     None, "high"),
    ("claw-machine-360", "x360", "Claw Machine", None, None, "game", ["Gunz4Hire"],
     "Simulador autoral de máquina de garra para Xbox 360.",
     None, "high"),
    ("little-more-intense-snake", "x360", "A Little More Intense Snake", None, None, "game", ["Gunz4Hire"],
     "Versão turbinada do clássico Snake para Xbox 360.",
     None, "high"),
    ("redpill-360", "x360", "RedPill", None, None, "game", ["Decimation Studios"],
     "Jogo de plataforma autoral simples para Xbox 360.",
     None, "high"),
    ("xbox-invaders", "x360", "Xbox Invaders", None, None, "game", ["MaesterRowen Studio"],
     "Jogo experimental autoral no estilo Space Invaders para Xbox 360.",
     None, "high"),
]

# ===========================================================================
# XBOX 360 — UTILITÁRIOS, FERRAMENTAS DE NAND/RGH E MÍDIA
# ===========================================================================
ENTRIES += [
    ("dashlaunch", "x360", "DashLaunch", None, None, "utility", ["cOz"],
     "Configura o boot do console modificado: dashboard padrão, plugins, ventoinhas e patches.",
     None, "high"),
    ("xell", "x360", "XeLL (Xenon Linux Loader)", "Free60", None, "utility", ["Free60 Project"],
     "Bootloader de segundo estágio que carrega ELF pela rede, CD ou USB e dá boot em Linux.",
     "https://github.com/Free60Project/xell", "high"),
    ("xell-reloaded", "x360", "XeLL Reloaded", "Free60", None, "utility", ["Free60 Project"],
     "Versão em dois estágios do XeLL, compatível com JTAG e com o Reset Glitch Hack.",
     "https://github.com/Free60Project/xell-reloaded", "high"),
    ("xellous", "x360", "XeLLous", "Free60", None, "utility", ["Redline99"],
     "Modificação do XeLL que adiciona gravação de NAND e servidor HTTP de chaves.",
     "https://free60.org/", "high"),
    ("xelllaunch", "x360", "XellLaunch", None, None, "utility", ["Comunidade Xbox 360"],
     "Atalho que inicia o XeLL a partir do dashboard, sem desligar o console.",
     None, "high"),
    ("libxenon", "x360", "libXenon", "Free60", None, "utility", ["Free60 Project"],
     "Biblioteca open source e legal para escrever homebrew de Xbox 360 sem código do XDK.",
     "https://github.com/Free60Project/libxenon", "high"),
    ("libxtaf", "x360", "libxtaf", "Free60", None, "utility", ["Free60 Project"],
     "Biblioteca para manipular o sistema de arquivos FATX/XTAF do Xbox 360.",
     "https://github.com/Free60Project/libxtaf", "high"),
    ("xenon-toolchain", "x360", "Xenon Toolchain", "Free60", None, "utility", ["Free60 Project"],
     "Cadeia de compilação cruzada PowerPC usada para construir homebrew de Xbox 360.",
     "https://free60.org/", "high"),
    ("xebuild", "x360", "xeBuild", None, None, "utility", ["Comunidade Xbox 360"],
     "Constrói a imagem de NAND modificada usada em consoles JTAG e RGH.",
     None, "high"),
    ("xebuild-gui", "x360", "xeBuild GUI", None, None, "utility", ["InsaneNutter", "Swizzy"],
     "Interface gráfica para o xeBuild, simplificando a montagem da NAND.",
     None, "high"),
    ("j-runner", "x360", "J-Runner (with Extras)", None, None, "utility", ["octal450"],
     "Ferramenta de PC que lê, grava e monta imagens de NAND para exploits JTAG/RGH.",
     None, "high"),
    ("nandpro", "x360", "NandPro", None, None, "utility", ["Tiros"],
     "Utilitário clássico de linha de comando para dump e flash da NAND do Xbox 360.",
     None, "high"),
    ("simple-360-nand-flasher", "x360", "Simple 360 NAND Flasher", None, None, "utility", ["Swizzy"],
     "Grava ou faz dump da NAND direto do console, a partir de um dashboard homebrew.",
     None, "high"),
    ("x360nandmanager", "x360", "x360NANDManager", None, None, "utility", ["Swizzy"],
     "Biblioteca .NET para gerenciar NAND via NANDPro, JR-Programmer, PIC, AVR ou FTDI.",
     "https://github.com/Swizzy/x360NANDManager", "high"),
    ("nandcompare", "x360", "NandCompare", None, None, "utility", ["Free60 Project"],
     "Compara dumps de NAND para validar e reparar leituras ruins.",
     "https://free60.org/", "high"),
    ("360flashtool", "x360", "360FlashTool", None, None, "utility", ["Comunidade Xbox 360"],
     "Exibe, descriptografa e extrai partes de uma imagem de NAND do Xbox 360.",
     "https://free60.org/", "high"),
    ("rawflash", "x360", "Rawflash", None, None, "utility", ["Free60 Project"],
     "Aplicativo libXenon que grava imagens raw (sem remapeamento) na NAND.",
     "https://free60.org/", "high"),
    ("freemyxe", "x360", "FreeMyXe", None, None, "utility", ["FreeMyXe"],
     "Aplica os patches de liberdade ao kernel e ao hypervisor para permitir homebrew.",
     "https://github.com/FreeMyXe/FreeMyXe", "high"),
    ("xeunshackle", "x360", "XeUnshackle", None, None, "utility", ["Byrom90"],
     "Usa o exploit Bad Update para aplicar patches de hypervisor e carregar o DashLaunch.",
     "https://github.com/Byrom90/XeUnshackle", "high"),
    ("xbox360badupdate", "x360", "Bad Update", None, None, "utility", ["grimdoomer"],
     "Exploit de software que roda homebrew em Xbox 360 de fábrica, sem solda nem modchip.",
     "https://github.com/grimdoomer/Xbox360BadUpdate", "high"),
    ("party-buffalo", "x360", "Party Buffalo Drive Explorer", None, None, "utility", ["CLK"],
     "Explorador de HD e pendrive FATX do Xbox 360 no Windows.",
     None, "high"),
    ("velocity-360", "x360", "Velocity", None, None, "utility", ["Stevie Hetelekides", "Adam Spindler"],
     "Editor multiplataforma de pacotes STFS, perfis e saves do Xbox 360.",
     "https://github.com/hetelek/Velocity", "high"),
    ("le-fluffie", "x360", "Le Fluffie", None, None, "utility", ["DJ Shepherd"],
     "Abre e reassina pacotes STFS: perfis, saves, conteúdo XBLA e DLC.",
     "https://archive.org/details/le-fluffie", "high"),
    ("360-content-manager", "x360", "360 Content Manager", None, None, "utility", ["xamphear"],
     "Organiza, renomeia e envia por FTP conteúdo STFS/SVOD (XBLA, DLC, GOD).",
     None, "high"),
    ("modio", "x360", "Modio", None, None, "utility", ["GameTuts"],
     "Editor clássico de saves e transferência de arquivos do Xbox 360.",
     None, "high"),
    ("horizon-360", "x360", "Horizon", None, None, "utility", ["WeMod"],
     "Ferramenta gratuita de edição de saves e perfis do Xbox 360.",
     "https://www.wemod.com/horizon", "medium"),
    ("iso2god", "x360", "Iso2God", None, None, "utility", ["Comunidade Xbox 360"],
     "Converte imagens ISO de jogos para o formato Games on Demand instalável no HD.",
     "https://github.com/r4dius/Iso2God", "high"),
    ("iso2god-rs", "x360", "iso2god-rs", None, None, "utility", ["iliazeus"],
     "Reimplementação open source em Rust do conversor ISO para Games on Demand.",
     "https://github.com/iliazeus/iso2god-rs", "high"),
    ("xm360", "x360", "XM360", None, None, "utility", ["node21 (Team XeDev)"],
     "Destrava conteúdo STFS do Marketplace, como demos de XBLA, DLC e title updates.",
     None, "high"),
    ("god-unlocker", "x360", "GOD Unlocker XB360", None, None, "utility", ["Byrom"],
     "Destrava conteúdo SVOD do Marketplace: Games on Demand e jogos do Xbox original.",
     None, "high"),
    ("nxe2god", "x360", "NXE2GOD", None, None, "utility", ["Dstruktiv (Team XeDev)"],
     "Converte jogos já instalados no HD para o formato Games on Demand, dispensando o disco.",
     None, "high"),
    ("xextool", "x360", "XexTool", None, None, "utility", ["Comunidade Xbox 360"],
     "Extrai e manipula executáveis XEX do Xbox 360.",
     "https://github.com/Team-Resurgent/XexTool", "high"),
    ("fakeanim", "x360", "Fakeanim", None, None, "utility", ["Comunidade Xbox 360"],
     "Substitui a animação de boot do Xbox 360 por uma personalizada.",
     None, "high"),
    ("lightshow-360", "x360", "Lightshow", None, None, "utility", ["Derf"],
     "Testa o Ring of Light e o LED de energia e cria shows de luz na animação de boot.",
     None, "high"),
    ("gamepad-36ster", "x360", "GamePad 36ster", None, None, "utility", ["Mr.SuS.60"],
     "Testa todos os botões, analógicos e vibração de um controle de Xbox 360.",
     None, "high"),
    ("hiddriver360", "x360", "hiddriver360", None, None, "utility", ["EinTim"],
     "Driver HID experimental que habilita controles de terceiros sem dongle nem patch de USB.",
     None, "high"),
    ("usbdsecpatch", "x360", "UsbdSecPatch", None, None, "utility", ["InvoxiPlayGames"],
     "Plugin do DashLaunch que libera o uso de qualquer controle USB no console.",
     None, "high"),
    ("hdd-compat-fixer", "x360", "HDD Compatibility Fixer", None, None, "utility", ["Dstruktiv (Team XeDev)"],
     "Cria a partição necessária para instalar o emulador de retrocompatibilidade em HDs não oficiais.",
     None, "high"),
    ("xpg-chameleon", "x360", "XPG Chameleon", None, None, "utility", ["Team XPG"],
     "Aplicativo de banco de dados de cheats para jogos de Xbox 360.",
     None, "high"),
    ("xna-offline", "x360", "XNA Offline", "Microsoft XNA", None, "utility", ["Natelx"],
     "Permite rodar offline os jogos indie feitos em XNA depois do fim do Xbox Live Indie Games.",
     None, "high"),
    ("xenon-dumper", "x360", "Xenon Dumper", None, None, "utility", ["Byrom90"],
     "Extrai do console os arquivos e chaves necessários ao emulador de baixo nível Xenon.",
     None, "high"),
    ("homebrew-store-360", "x360", "Xbox 360 Homebrew Store", None, 2024, "utility", ["Derf"],
     "Script Lua para o Aurora que baixa e instala homebrew, emuladores e apps direto no console.",
     "https://consolemods.org/wiki/Xbox_360:Homebrew_Store", "high"),
    ("aurora-repo-browser", "x360", "Aurora Repo Browser", None, None, "utility", ["Phoenix Team"],
     "Navegador de repositórios de scripts embutido no dashboard Aurora.",
     None, "high"),
    ("disc-ripper-360", "x360", "Disc Ripper (ConsoleMods)", None, None, "utility", ["Derf"],
     "Script do Aurora que copia o conteúdo de um disco para uma pasta no Xbox 360.",
     None, "high"),
    ("milkytracker-360", "x360", "MilkyTracker 360", None, None, "utility", ["Lantus"],
     "Port do MilkyTracker, software de criação de música em módulos, para Xbox 360.",
     None, "high"),
    ("ffplay-360", "x360", "FFPlay 360", "FFmpeg", None, "media", ["Cancerous", "JQE"],
     "Tocador de mídia baseado em FFmpeg para Xbox 360 modificado.",
     None, "high"),
    ("xmplayer-360", "x360", "XMPlayer", "MPlayer", None, "media", ["ced2911"],
     "Port do MPlayer para Xbox 360 via libXenon.",
     "https://free60.org/", "high"),
    ("xbmc360", "x360", "XBMC360", "Kodi (software)", None, "media", ["brentdc-nz"],
     "Port inacabado do XBMC4Xbox para o Xbox 360, feito com o SDK oficial.",
     "https://github.com/brentdc-nz/XBMC-360", "medium"),
    ("zlx-browser", "x360", "ZLX Browser", None, None, "utility", ["ced2911"],
     "Gerenciador de arquivos para Xbox 360 construído sobre a biblioteca ZLX.",
     "https://free60.org/", "high"),
    ("linux-360", "x360", "Linux (Xbox 360)", "Free60", None, "utility", ["Free60 Project"],
     "Distribuições Linux (Debian/Ubuntu) que dão boot no Xbox 360 através do XeLL.",
     "https://github.com/Free60Project/linux-kernel-xbox360", "high"),
    ("xenosfb", "x360", "xenosfb", "Free60", None, "utility", ["Free60 Project"],
     "Driver de vídeo do X.org para a GPU Xenos do Xbox 360 sob Linux.",
     "https://github.com/Free60Project/xenosfb", "high"),
]


# ---------------------------------------------------------------------------
# CONSTRUCAO + VALIDACAO
# ---------------------------------------------------------------------------
SLUG_RE = re.compile(r"^[a-z0-9-]+$")


def build():
    out, seen = [], set()
    for i, row in enumerate(ENTRIES):
        if len(row) != 10:
            raise SystemExit("entrada %d tem %d campos (esperado 10): %r" % (i, len(row), row[:2]))
        slug, console, title, wiki, year, category, devs, desc, url, verified = row

        if not SLUG_RE.match(slug):
            raise SystemExit("slug invalido: %r" % slug)
        _id = "hb-" + slug
        if _id in seen:
            raise SystemExit("id duplicado: %s" % _id)
        seen.add(_id)

        if console not in CONSOLES:
            raise SystemExit("%s: console invalido %r" % (_id, console))
        if category not in CATEGORIES:
            raise SystemExit("%s: category invalida %r" % (_id, category))
        if verified not in VERIFIED:
            raise SystemExit("%s: verified invalido %r" % (_id, verified))
        if not title or not title.strip():
            raise SystemExit("%s: title vazio" % _id)
        if not desc or not desc.strip():
            raise SystemExit("%s: description vazia" % _id)
        if year is not None and not (1999 <= year <= 2026):
            raise SystemExit("%s: year fora da faixa: %r" % (_id, year))
        if not isinstance(devs, list):
            raise SystemExit("%s: developers deve ser lista" % _id)

        out.append({
            "id": _id,
            "platform": "homebrew",
            "console": console,
            "title": title.strip(),
            "wiki": wiki,
            "year": year,
            "category": category,
            "developers": list(devs),
            "description": desc.strip(),
            "url": url,
            "image": None,
            "verified": verified,
        })

    out.sort(key=lambda d: (d["console"], d["category"], d["title"].lower()))
    return out


def main():
    data = build()

    consoles = Counter(d["console"] for d in data)
    cats = Counter(d["category"] for d in data)

    # requisitos minimos pedidos no briefing
    problems = []
    if len(data) < 140:
        problems.append("menos de 140 entradas (%d)" % len(data))
    for c in ("xbox", "x360"):
        if consoles[c] + consoles["both"] < 50:
            problems.append("cobertura insuficiente de %s (%d)" % (c, consoles[c]))
    faltando = CATEGORIES - set(cats)
    if faltando:
        problems.append("categorias sem entradas: %s" % ", ".join(sorted(faltando)))
    if problems:
        raise SystemExit("FALHA NA VALIDACAO: " + "; ".join(problems))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    # build_homebrew_extra.py acrescenta entradas NO MESMO arquivo. Reescrever
    # so com a tabela ENTRIES deste script apagaria todas elas.
    if os.path.exists(OUT):
        with open(OUT, encoding="utf-8") as f:
            atual = json.load(f)
        meus = {d["id"] for d in data}
        extras = [d for d in atual if d["id"] not in meus]
        if extras and "--merge" not in sys.argv:
            raise SystemExit("RECUSADO: %s tem %d entradas de outra origem "
                             "(build_homebrew_extra.py). Rode com --merge." % (OUT, len(extras)))
        data = data + extras
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)

    print("gravado data/homebrew.json  ->  %d entradas (%.1f KB)"
          % (len(data), os.path.getsize(OUT) / 1024))
    print("  por console : " + "  ".join("%s=%d" % kv for kv in sorted(consoles.items())))
    print("  por category: " + "  ".join("%s=%d" % kv for kv in sorted(cats.items())))
    print("  com wiki    : %d" % sum(1 for d in data if d["wiki"]))
    print("  com url     : %d" % sum(1 for d in data if d["url"]))
    print("  com year    : %d" % sum(1 for d in data if d["year"]))
    print("  verified    : " + "  ".join("%s=%d" % kv for kv in
                                         sorted(Counter(d["verified"] for d in data).items())))


if __name__ == "__main__":
    main()
